### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by nielssch** [HormyAJP/influxdb_google_sheets#1]
I was really happy to find a script doing exactly what I was looking for. Unfortunately I am getting an error message and cannot see how to fix it :-( Any idea why I am getting this message just behind the correct query URL?
![influx script error](https://user-images.githubusercontent.com/15388338/103371631-3fdc7e80-4ad0-11eb-9b8d-ded1496d35a1.png)

**Comment by HormyAJP** [comment]
That's the line which makes the the HTTPS call to the Influx URL. Can you paste the whole error please? The section you've shown is just the stack trace.

**Comment by nielssch** [comment]
Thanks for your speedy response. The whole message looks like this
![Error message](https://user-images.githubusercontent.com/15388338/103407721-f6d40b00-4b5f-11eb-98c2-f40331ca47a6.png)
When using the URL http://192.168.178.14:8086/query?&db=weichwasser&q=SELECT%20*%20FROM%20softliqSC18 
in a browser window, the data is showing just fine.

**Comment by HormyAJP** [comment]
The problem here is your Influx instance is running on a local IP address: 192.168.178.14. However, the query will be executed by Google's servers. In order for this to work your Influx instance needs to be publicly accessible. Try using ngrok as a quick fix.

**Comment by nielssch** [comment]
Oh, stupid me. Thanks a lot. This really should have crossed my mind. Of course, please excuse me.
